Refactor error handling
It will now look like this if `e.display_causes_and_backtrace()` is used:

```
Error: JsonRpc getblock failed
  caused by: JSON decode error: expected value at line 1 column 1
```